version: "3.7"
services:

  db:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 9094:8080

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    ports:
      - 9096:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ernesto
      PGADMIN_DEFAULT_PASSWORD: example

