version: "3.7"
services:

  db:
    build: .
    image: osmanirosado/dvdrental-database:2019.05
    ports:
      - "127.0.0.1:9092:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_PORT: 5432

  adminer:
    image: adminer:4.8.1
    ports:
      - "127.0.0.1:9094:8080"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "127.0.0.1:9096:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domanin.com
      PGADMIN_DEFAULT_PASSWORD: example
    depends_on:
      - db

