version: "3.7"
services:

  db:
    build: .
    image: osmanirosado/dvdrental-database:2019.05
    restart: always
    ports:
      - 9092:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_PORT: 5432

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 9094:8080
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    ports:
      - 9096:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ernesto
      PGADMIN_DEFAULT_PASSWORD: example
    depends_on:
      - db

