version: "3.7"
services:

  db:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 9094:8080
